title: PubGyu Blog
author:
  name: pubgyu
  email: pubgyu@gmail.com
description: pubgyu의 블로그

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  pubgyu

# theme
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# server

# baseurl
baseurl: /
